/*****************************************************************************
* File Name        : main.c
*
* Description      : This source file contains the main routine for CM55 CPU
*
* Related Document : See README.md
*
******************************************************************************
* Copyright 2023-2024, Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
*
* This software, including source code, documentation and related
* materials ("Software") is owned by Cypress Semiconductor Corporation
* or one of its affiliates ("Cypress") and is protected by and subject to
* worldwide patent protection (United States and foreign),
* United States copyright laws and international treaty provisions.
* Therefore, you may use this Software only as provided in the license
* agreement accompanying the software package from which you
* obtained this Software ("EULA").
* If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
* non-transferable license to copy, modify, and compile the Software
* source code solely for use in connection with Cypress's
* integrated circuit products.  Any reproduction, modification, translation,
* compilation, or representation of this Software except as specified
* above is prohibited without the express written permission of Cypress.
*
* Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Cypress
* reserves the right to make changes to the Software without notice. Cypress
* does not assume any liability arising out of the application or use of the
* Software or any product or circuit described in the Software. Cypress does
* not authorize its products for use in any products where a malfunction or
* failure of the Cypress product may reasonably be expected to result in
* significant property damage, injury or death ("High Risk Product"). By
* including Cypress's product in a High Risk Product, the manufacturer
* of such system or application assumes all risk of such use and in doing
* so agrees to indemnify Cypress against all liability.
*****************************************************************************/

#include "cy_pdl.h"
#include "cyhal.h"
#include "cybsp.h"
#include "cy_retarget_io.h"
#include "ipc_communication.h"

/*****************************************************************************
* Macros
*****************************************************************************/
#define BTN_INIT_VAL          (0U)
#define BTN_MSG_START         (1U)
#define BTN_MSG_STOP          (2U)
#define BTN_DEBOUNCE_DELAY_MS (100U)

/*****************************************************************************
* Global Variables
*****************************************************************************/
/* Message variables */
static volatile bool button_flag ;
static volatile bool button_pressed ;
static volatile uint32_t button_status = BTN_INIT_VAL;


/*****************************************************************************
* Function Prototypes
*****************************************************************************/
static void button_isr_handler(void *arg, cyhal_gpio_event_t event);

/*****************************************************************************
* Function Definitions
*****************************************************************************/
static cyhal_gpio_callback_data_t cb_data =
{
    .callback = button_isr_handler,
    .callback_arg = NULL
};

/* MCWDT Object [used by CM33] */
static cyhal_resource_inst_t mcwdt_0 =
{
    .type = CYHAL_RSC_LPTIMER,
    .block_num = 0
};


/*****************************************************************************
* Function Name: main
******************************************************************************
* Summary:
* This is the main function for CM55 CPU.
* It adds START/STOP commands to IPC command queue on alternate button presses.
* It reads the message queue and prints the random number generated by CM33 CPU
*
* Parameters:
*  void
*
* Return:
*  int
*
*****************************************************************************/
int main(void)
{
	/* Local variables */
	cy_rslt_t result;
    cyhal_ipc_t task1_queue1;
    cyhal_ipc_t task1_queue2;

    uint32_t task1_cmd;
    uint32_t task1_msg;

	
    /* Initialize the device and board peripherals */
    result = cybsp_init();

    /* Board init failed. Stop program execution */
    if (CY_RSLT_SUCCESS != result)
    {
        CY_ASSERT(0);
    }

    /* Reserve the MCWDT used by the CM33 to avoid conflicts if a LPTIMER is
                to be added in the CM55 */
        result = cyhal_hwmgr_reserve(&mcwdt_0);
        if (CY_RSLT_SUCCESS != result)
        {
            CY_ASSERT(0);
        }

    /* Enable global interrupts */
    __enable_irq();

    /* Initialize retarget-io to use the debug UART port */
    result = cy_retarget_io_init(CYBSP_DEBUG_UART_TX, CYBSP_DEBUG_UART_RX, CY_RETARGET_IO_BAUDRATE);
    if (CY_RSLT_SUCCESS != result)
    {
        CY_ASSERT(0);
    }



    /* Initialize the User Button */
	result = cyhal_gpio_init(CYBSP_USER_BTN, CYHAL_GPIO_DIR_INPUT,
					CYBSP_USER_BTN_DRIVE, CYBSP_BTN_OFF);

	if (CY_RSLT_SUCCESS != result)
	{
		CY_ASSERT(0);
	}
	cyhal_gpio_enable_event(CYBSP_USER_BTN, CYHAL_GPIO_IRQ_RISE, CYHAL_ISR_PRIORITY_DEFAULT, true);
	cyhal_gpio_register_callback(CYBSP_USER_BTN, &cb_data);

	result = cyhal_gpio_init(CYBSP_USER_LED, CYHAL_GPIO_DIR_OUTPUT,
								 CYHAL_GPIO_DRIVE_STRONG, CYBSP_LED_STATE_OFF);

    /* Initialize IPC and get handles */
	cyhal_ipc_init(CYHAL_IPC_NEVER_TIMEOUT);

	result = cyhal_ipc_queue_get_handle(&task1_queue1, CMD_CHANNEL_NUM, QUEUE1_NUM);
	result = cyhal_ipc_queue_get_handle(&task1_queue2, MSG_CHANNEL_NUM, QUEUE2_NUM);

	cyhal_ipc_queue_enable_event(&task1_queue2, CYHAL_IPC_QUEUE_WRITE, (uint8_t)IPC_QUEUE_IRQ_PRIORITY, true);

	/* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
	printf("\x1b[2J\x1b[;H");

	printf("****************** \
	PSOC Edge MCU: IPC Queues Example \
	****************** \r\n\n");

	printf("<Press the USER BTN1 once to start random number generation, press again to stop>\r\n");

	task1_cmd = IPC_CMD_INIT;
	cyhal_ipc_queue_put(&task1_queue1, &task1_cmd, CYHAL_IPC_NEVER_TIMEOUT);

	button_flag = false;
	button_pressed = false;

	/* Main loop */
	for(;;)
	{

		cyhal_syspm_sleep();

		if (button_flag)
		{
			/* Button debounce delay */
			cyhal_system_delay_ms(BTN_DEBOUNCE_DELAY_MS);

			if ((BTN_INIT_VAL == button_status) || (BTN_MSG_STOP == button_status))
			{
				button_status = BTN_MSG_START;
			}
			else
			{
				button_status = BTN_MSG_STOP;
			}

			button_flag = false;
			button_pressed = true;

		}

		/* Check if the button was pressed */
		if (BTN_MSG_STOP == button_status)
		{
			if (button_pressed)
			{

				cyhal_ipc_queue_reset(&task1_queue1);
				cyhal_ipc_queue_reset(&task1_queue2);


				button_pressed = false;
				printf("<---Stop--->\n\r");

				cyhal_gpio_write(CYBSP_USER_LED, CYBSP_LED_STATE_OFF);

				task1_cmd = IPC_CMD_STOP;
				result = cyhal_ipc_queue_put(&task1_queue1, &task1_cmd, CYHAL_IPC_NEVER_TIMEOUT);
				if (CY_RSLT_SUCCESS != result)
				{
					CY_ASSERT(0);
				}

			}

		}
		else if (BTN_MSG_START == button_status)
		{
			if (button_pressed)
			{
				button_pressed = false;
				printf("<---Start--->\n\r");

				cyhal_gpio_write(CYBSP_USER_LED, CYBSP_LED_STATE_ON);

				task1_cmd = IPC_CMD_START;
				result = cyhal_ipc_queue_put(&task1_queue1, &task1_cmd, CYHAL_IPC_NEVER_TIMEOUT);
				if (CY_RSLT_SUCCESS != result)
				{
					CY_ASSERT(0);
				}

			}

			if (cyhal_ipc_queue_count(&task1_queue2))
			{
				if (CY_RSLT_SUCCESS == (cyhal_ipc_queue_get(&task1_queue2, &task1_msg, CYHAL_IPC_NEVER_TIMEOUT)))
				{
					printf("0x%.8x\n\r", (unsigned int) task1_msg);
				}
			}
		}
	} /* close main loop */

    return 0;
}



/*******************************************************************************
* Function Name: button_isr_handler
********************************************************************************
* Summary:
*  Button ISR handler. Set a flag to be processed in the main loop.
*
* Parameters:
*  arg: not used
*  event: event that occurred
*
*******************************************************************************/
static void button_isr_handler(void *arg, cyhal_gpio_event_t event)
{
    CY_UNUSED_PARAMETER(arg);
    CY_UNUSED_PARAMETER(event);

    button_flag = true;
}

/* [] END OF FILE */
